server:
  port: 8081
spring:
  cloud:
    config:
      server:
        git:
          default-label: auth-jwt
          uri: https://github.com/yair1215/MicreoServicio-Tutorial
          search-paths: config-data
  application:
    name: config-service
